# Generated by Django 2.2 on 2020-11-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0002_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
